### ISSUE TITLE
Artifactory Ansible -  Failed resolving master key, Service wont start 

### ISSUE THREAD

**Issue by localleon** [jfrog/JFrog-Cloud-Installers#254] opened 2022-12-18 19:22 UTC
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Which installer**:
Ansible Collection 

**Which product and version** (eg: ansible & collection version - 7.24.2):
latest ansible collection and ansible 

**Which operating system and version**(eg: ubuntu & version - 20.4):
Ubuntu 22.04 

**Which product license** (Enterprise/Pro):
Enterprise

**JFrog support reference** (if already raised with support team): 

**What happened**:
Artifactory won't start after a fresh install with the Ansible Collection. Nginx says "503 - Bad Gateway" for the user and in the Nginx-Logs we see the following: 

```
root@lraus-lab0:/opt/jfrog/artifactory/var/log# cat /var/log/nginx/artifactory-error.log
2022/12/18 19:11:35 [error] 13219#13219: *89 connect() failed (111: Unknown error) while connecting to upstream, client: 87.169.19.160, server: test.artifactory.com, request: "GET /ui/ HTTP/1.1", upstream: "http://127.0.0.1:8082/ui/", host: "5.75.162.203"
2022/12/18 19:11:35 [error] 13219#13219: *89 connect() failed (111: Unknown error) while connecting to upstream, client: 87.169.19.160, server: test.artifactory.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8082/favicon.ico", host: "5.75.162.203", referrer: "http://5.75.162.203/ui/"
```

In the Router-Service-Log on can see that the Master-Key can somehow not be decrypted: 

```log
root@lraus-lab0:/opt/jfrog/artifactory/var/log# cat router-service.log
2022-12-18T18:47:33.266Z [jfrou] [INFO ] [0d96be6e3486ae79] [bootstrap.go:77               ] [main                ] [] - Router (jfrou) service initialization started. Version: 7.50.0-1 Revision: 027126ff8a8e43e22ade6fbbf02d8226df457cba PID: 5398 Home: /opt/jfrog/artifactory
2022-12-18T18:47:33.266Z [jfrou] [INFO ] [0d96be6e3486ae79] [bootstrap.go:80               ] [main                ] [] - JFrog Router IP: 127.0.1.1
2022-12-18T18:49:33.268Z [jfrou] [FATAL] [0d96be6e3486ae79] [bootstrap.go:99               ] [main                ] [] - Failed resolving master key: encoding/hex: invalid byte: U+0054 'T'
```

The Master-Key was successfully deployed by the ansible role. 
![image](https://user-images.githubusercontent.com/28186014/208314999-53f28ac8-a84e-4092-8e27-a2f069cd11f2.png)

After some times the "artifcatory"-Service fails. With a ``systemctl restart artifcatory` the service reboots and the webinterface is now shown! 

**What you expected to happen**:

The service should have been started immediatly. A manual restart should not be necessary! 

**How to reproduce it** (as minimally and precisely as possible):

Execute the following playbook on an Ubuntu 20.04 machine. 

```yaml
---
- hosts: all
  become: true
  become_method: sudo
  vars: 
    ## Note: These values are global and have precedence over role/<product>/defaults/main.yaml
    ## For production deployments, You may want to generate your master and join keys and apply it to all the nodes.
    master_key: bbc8cdfbf6f999a7500e4e43cf620b9d570965c0af17623c749949b18717398a
    join_key: 94808af081282886c54644de48e74c469fac381793695228a0eaf43edf6c10f7

    jfrog_url: >-
      "http://{{ hostvars[groups['artifactory_servers'][0]]['ansible_host'] }}:8082"

    ## Products enabled
    artifactory_enabled: true
    xray_enabled: false
    distribution_enabled: false
    insight_enabled: false
    postgres_enabled: true

    # Artifactory DB details
    artifactory_db_type: postgresql
    artifactory_db_driver: org.postgresql.Driver
    artifactory_db_name: artifactory
    artifactory_db_user: artifactory
    artifactory_db_password: password
    artifactory_db_url: >-
      jdbc:postgresql://{{ hostvars[groups['postgres_servers'][0]]['ansible_host'] }}:5432/{{ artifactory_db_name }}


    # Postgresql users and databases/schemas
    database:
      artifactory:
        name: "{{ artifactory_db_name }}"
        owner: "{{ artifactory_db_user }}"
        username: "{{ artifactory_db_user }}"
        password: "{{ artifactory_db_password }}"
        enabled: "{{ artifactory_enabled }}"

  tasks: 
    - name: Print Jfrog jfrog
      debug: 
        msg: "{{ jfrog_url }}"

  roles:
    - role: jfrog.platform.postgres
      when: postgres_enabled | bool
    - role:  jfrog.platform.artifactory
      when: artifactory_enabled | bool
```

**Anything else we need to know**:

Already tried other OS (e.g Ubuntu 20.04) and

**Comment by shahiinn** [comment] 2022-12-23 07:46
@localleon : Is the issue still persist?
Though you have mentioned the latest ansible collection. Can you specify the exact version of it?
Do you have any customizations done to the system.yaml file?

**Comment by itssiri** [comment] 2022-12-30 09:55
@localleon , gentle reminder..

**Comment by localleon** [comment] 2022-12-31 09:46
Hey,

sorry for the late reply. I was on a holiday leave. 

The issue still persists. 

```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/lraus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lraus/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/lraus/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lraus/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

Using 
-  community.general-6.1.0
-  jfrog.platform-10.10.1

**Comment by chukka** [comment] 2023-01-27 03:07
@localleon we are unable to reproduce this issue . Please provide detailed steps to reproduce  the issue

**Comment by itssiri** [comment] 2023-03-17 10:28
@localleon , gentle reminder..   Let us know if we can close this issue.

**Closed** 2023-03-17 10:39 UTC
